[tool.commitizen]
name = "cz_conventional_commits"
version = "0.0.1"
tag_format = "v$version"
annotated_tag = true
update_changelog_on_bump = true
changelog_file = "CHANGELOG.md"
changelog_incremental = true
bump_message = "ci: release v$current_version"
version_files = [
  "backend/pyproject.toml",
  "ingestors/eventbrite/pyproject.toml",
  "ingestors/meetup/pyproject.toml",
  "ingestors/openweathermap/pyproject.toml",
  "ingestors/ticketmaster/pyproject.toml",
  "ingestors/tripadvisor/pyproject.toml",
  "kafka/pyproject.toml",
]
major_version_zero = false
