# Usar la imagen ligera de Python 3.11
FROM python:3.11-slim

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar el archivo de código al contenedor
COPY app.py .

# Comando por defecto que se ejecuta al iniciar el contenedor
CMD ["python", "app.py"]
