# config/topics.yaml

# Definición de topics para todos los ambientes
# Puedes tener configuraciones específicas por ambiente si es necesario,
# pero para temas de escalabilidad, es mejor mantener las configs básicas
# (particiones/replicación) consistentes, y manejar diferencias en el código
# si un ambiente necesita un factor de replicación menor por ej.

# Para este ejemplo, asumimos que todos los ambientes usan estas definiciones
# o que el script de creación adapta el replication_factor según el ambiente
# (ej. 1 para dev, 3 para prod).

topics:
  raw_events:
    partitions: 6
    replication_factor: 1 # Esto se ajustará en el código para prod (3)
    configs:
      cleanup.policy: "delete"
      retention.ms: "604800000" # 7 días
      segment.bytes: "1073741824" # 1GB

  raw_places:
    partitions: 6
    replication_factor: 1 # Ajuste para prod (3)
    configs:
      cleanup.policy: "delete"
      retention.ms: "604800000" # 7 días

  raw_weather:
    partitions: 3
    replication_factor: 1 # Ajuste para prod (3)
    configs:
      cleanup.policy: "delete"
      retention.ms: "259200000" # 3 días (3 * 24 * 60 * 60 * 1000 = 259,200,000 ms)