default: &default_config
  # Configuración común para todos los ambientes
  kafka_version: "7.5.0" # Versión de Confluent Platform
  # CRÍTICO: Deshabilitar auto-creación de topics si quieres control manual
  # Esta configuración se aplica a los brokers de Kafka, no al cliente AdminClient
  # En Docker Compose, se setea como variable de entorno KAFKA_AUTO_CREATE_TOPICS_ENABLE
  auto_create_topics_broker_setting: "false"

  # Configuración general de cliente (productor/consumidor)
  client_id_prefix: "ingestor-app"
  
  # Configuración para la creación/verificación de topics
  topic_creation_timeout_ms: 30000 # Default 30 segundos para crear topics
  max_retries_create_topics: 5
  retry_backoff_ms: 1000 # 1 segundo

development:
  <<: *default_config
  brokers: "kafka:9092"
  client_id: "dev-ingestor-app"
  security_protocol: "SASL_PLAINTEXT" # Mantener SASL_PLAINTEXT para desarrollo local (con autenticación)
  sasl_mechanism: "SCRAM-SHA-512"
  sasl_username: ${KAFKA_USERNAME} # Asegúrate de que estas credenciales estén en tu .env local
  sasl_password: ${KAFKA_PASSWORD} # Asegúrate de que estas credenciales estén en tu .env local
  # Propiedades del productor para idempotencia
  producer_properties:
    enable.idempotence: "true"
    acks: "all"
    retries: 2147483647
    max.in.flight.requests.per.connection: 5

staging:
  <<: *default_config
  brokers: "kafka-staging-01:9092,kafka-staging-02:9092"
  client_id: "staging-ingestor-app"
  security_protocol: "SASL_PLAINTEXT" # <--- CAMBIO: SASL_PLAINTEXT
  sasl_mechanism: "SCRAM-SHA-512"    # <--- AGREGADO: Mecanismo SASL
  sasl_username: "your_staging_username" # <--- AGREGADO: Define tu usuario para staging
  sasl_password: "your_staging_password" # <--- AGREGADO: Define tu contraseña para staging
  # --- ELIMINADAS las configuraciones SSL ---
  # ssl_ca_location: "/path/to/staging/ca.pem"
  # ssl_cert_location: "/path/to/staging/client.pem"
  # ssl_key.location: "/path/to/staging/client.key"
  topic_creation_timeout_ms: 60000
  max_retries_create_topics: 10
  retry_backoff_ms: 2000
  producer_properties:
    enable.idempotence: "true"
    acks: "all"
    retries: 2147483647
    max.in.flight.requests.per.connection: 5

production:
  <<: *default_config
  brokers: "kafka-prod-01:9092,kafka-prod-02:9092,kafka-prod-03:9092"
  client_id: "prod-ingestor-app"
  security_protocol: "SASL_PLAINTEXT" # <--- CAMBIO: SASL_PLAINTEXT
  sasl_mechanism: "SCRAM-SHA-512"    # <--- AGREGADO: Mecanismo SASL
  sasl_username: "your_prod_username" # <--- AGREGADO: Define tu usuario para production
  sasl_password: "your_prod_password" # <--- AGREGADO: Define tu contraseña para production
  # --- ELIMINADAS las configuraciones SSL ---
  # ssl_ca_location: "/path/to/prod/ca.pem"
  # ssl_cert_location: "/path/to/prod/client.pem"
  # ssl_key.location: "/path/to/prod/client.key"
  topic_creation_timeout_ms: 120000
  max_retries_create_topics: 15
  retry_backoff_ms: 3000
  producer_properties:
    enable.idempotence: "true"
    acks: "all"
    retries: 2147483647
    max.in.flight.requests.per.connection: 5